apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: bw8n5e3aw-java-springboot
  janus-idp.io/tekton: bw8n5e3aw-java-springboot
  backstage.io/kubernetes-id: bw8n5e3aw-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: bw8n5e3aw-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
